/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AngelaComponent {
    'items': any;
    'username': string;
  }
  interface AngelaComponentAttributes extends StencilHTMLAttributes {
    'items'?: any;
    'username'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AngelaComponent': Components.AngelaComponent;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'angela-component': Components.AngelaComponentAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLAngelaComponentElement extends Components.AngelaComponent, HTMLStencilElement {}
  var HTMLAngelaComponentElement: {
    prototype: HTMLAngelaComponentElement;
    new (): HTMLAngelaComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'angela-component': HTMLAngelaComponentElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'angela-component': HTMLAngelaComponentElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
