/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AtomComponent {
    'items': any;
    'username': string;
  }
  interface AtomComponentAttributes extends StencilHTMLAttributes {
    'items'?: any;
    'username'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AtomComponent': Components.AtomComponent;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'atom-component': Components.AtomComponentAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLAtomComponentElement extends Components.AtomComponent, HTMLStencilElement {}
  var HTMLAtomComponentElement: {
    prototype: HTMLAtomComponentElement;
    new (): HTMLAtomComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'atom-component': HTMLAtomComponentElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'atom-component': HTMLAtomComponentElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
